server.port=8080
spring.application.name=test-spring-boot-app
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application: ${spring.application.name}
